---
title: "Bivariate Viz"
---

Use this file to generate a professional looking **bivariate** visualization.  The visualization will not perfect the first time but you are expected to improve it throughout the semester especially after covering advanced topics such as effective viz.

```{r, include=FALSE}
library(tidyverse)
library(ggplot2)
library(mosaic)
data("Birthdays")
head(Birthdays)
```


```{r, echo=FALSE}
library(ggplot2)

ggplot(Birthdays, aes(x = date, y = births)) +
  geom_line() +
  labs(title = "Births over the years",
       caption = "Created by Isaiah, 4/25/2025, source: mosaicData package")
```

```{r,echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)

tuesdata <- tidytuesdayR::tt_load('2023-12-12')
## OR
tuesdata <- tidytuesdayR::tt_load(2023, week = 50)

holiday_movies <- tuesdata$holiday_movies
holiday_movie_genres <- tuesdata$holiday_movie_genres

# Option 2: Read directly from GitHub

holiday_movies <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-12-12/holiday_movies.csv')
holiday_movie_genres <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-12-12/holiday_movie_genres.csv')
```


```{r, echo=FALSE}

library(tidyverse)
library(ggplot2)
ggplot(holiday_movies , aes( x = year, y = runtime_minutes)) +
geom_line()+
   labs(
    title = "Length of movies over"~italic("Time"),
    caption = "Created by Isaiah, 4/25/2025, source: tidytuesday 2023-12-12", 
    x = "Year",
    y = "Movie length")  
  
```
