---
title: "Spatial Viz"
---

Use this file to generate a professional looking **spatial** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.

```{r, include=FALSE}
library(tibble)


# Isaiah's favorite places in Texas
favorite_Places <- tribble(
  ~place, ~long, ~lat, ~favorite,
  "home", -95.51390460140479 ,29.831800568188505, "yes", 
  "Sping Woods batting cages", -95.53209768244504, 29.80834390845172, "yes",
  "Garner State park", -99.74389070902677,29.599552733199022, "yes",
  "springspirit", -95.50372740252585, 29.832142909669244,"no",
  "Gym",  -95.50195869124816, 29.81584925293071, "no",
  "Grandma's", -95.54705812353582, 29.799837797973787, "no",
  "church", -95.45996377446176, 29.78260617451058, "no",
  "D'bats", -95.56941872353474, 29.833160713154612,  "no",
  "HEB", -95.53268245374554, 29.788162184326975, "no",
  "Lupe Tortilla", -95.6371158550073, 29.7935055368061, "no"
  )
```


```{r, include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
# Load required libraries
library(tidyverse)
library(openintro)
```


```{r, include=FALSE}
library(tidyverse)
library(ggplot2)
# Import starbucks location data
starbucks <- read.csv("https://mac-stat.github.io/data/starbucks.csv")
```


```{r, include=FALSE}
library(tidyverse)
library(ggplot2)
starbucks_us_by_state <- starbucks |>
  filter(Country == "US") |>
  count(State.Province) |>
  mutate(state_name = str_to_lower(abbr2state(State.Province)))
```


```{r, include=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(ggplot2)
census_pop_est_2018 <- read_csv("https://mac-stat.github.io/data/us_census_2018_state_pop_est.csv") |>
  separate(state, into = c("dot", "state"), extra = "merge") |>
  select(-dot) |>
  mutate(state = str_to_lower(state))

starbucks_with_2018_pop_est <-
  starbucks_us_by_state |>
  left_join(census_pop_est_2018,
    by = c("state_name" = "state")
  ) |>
  mutate(starbucks_per_10000 = (n / est_pop_2018) * 10000)
```
```{r, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
# Get the latitude and longitude coordinates of state boundaries
states_map <- map_data("state")

# Check it out
head(states_map)



```


```{r, echo=FALSE, message=FALSE, message=FALSE}
#| fig-height: 10
#| fig-width: 15
library(tidyverse)
library(ggplot2)
library(maps)
starbucks_us <- starbucks |> 
  filter(Country == "US")

states_map <- map_data("state")


ggplot(starbucks_with_2018_pop_est, aes(map_id = state_name, fill = starbucks_per_10000)) +
  geom_map(map = states_map) +
 geom_point(
    data = starbucks_us,
    aes(x = Longitude, y = Latitude),
    size = 2,
    alpha = 0.2,
    color = "orange", 
    inherit.aes = FALSE)+
  expand_limits(x = states_map$long, y = states_map$lat) +
   
  labs(
    title = "Starbucks Density Across the United States(for every 10,000 people)",
    caption = "Created by Isaiah, 4/27/2025, source: https://mac-stat.github.io/data/starbucks.csv")+
  scale_fill_gradientn( colors = c("blue", "lightblue"), values = scales::rescale(seq(0, 100, by = 5)))+
  theme(legend.title = element_blank())+
  theme_minimal()+
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )+
  theme(
    legend.text = element_text(size = 14) 
  )+
  theme(legend.title = element_blank())
 


 
        
```


```{r, echo=FALSE}
library(leaflet)

leaflet() %>%
  addTiles() %>%  
  addCircleMarkers(
    data = favorite_Places,
    lng = ~long, lat = ~lat,
    color = ~ifelse(favorite == "yes", "red", "darkblue"),
    radius = ~ifelse(favorite == "yes", 6, 4), 
    label = ~place,  # Adds hover labels
    labelOptions = labelOptions(noHide = FALSE, direction = "auto")
  ) %>%
  setView(lng = mean(favorite_Places$long), lat = mean(favorite_Places$lat), zoom = 6)
```

