---
title: "Exam 2"
editor: visual
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}


food_consumption <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2020/2020-02-18/food_consumption.csv')

tuesdata <- tidytuesdayR::tt_load('2020-02-18')
tuesdata <- tidytuesdayR::tt_load(2020, week = 8)


food_consumption <- tuesdata$food_consumption
```

```{r,echo=FALSE, message=FALSE, warning=FALSE}
library(tidytuesdayR)
tuesdata <- tt_load('2020-02-18')
fc <- tuesdata$food_consumption
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)

fcc <- food_consumption %>%
  select(-co2_emmission) %>%
  mutate(food_category = case_when(
    food_category == "Milk - inc. cheese" ~ "Dairy",
    food_category == "Nuts inc. Peanut Butter" ~ "Nuts",
    food_category == "Wheat and Wheat Products" ~ "Wheat",
    food_category == "Lamb & Goat" ~ "Lamb",
    TRUE ~ food_category
  ))

```



```{r, echo=FALSE, message=FALSE, warning=FALSE}
top5_countries <- fcc %>%
  group_by(country) %>%
  summarise(total_consumption = sum(consumption, na.rm = TRUE)) %>%
  arrange(desc(total_consumption)) %>%
  slice_head(n = 5)

```






```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(readr)   
library(scales)

ggplot(top5_countries, aes(x = reorder(country, total_consumption), y = total_consumption)) +
  geom_col(fill = "skyblue") +
  coord_flip() +
  labs( title = "Top 5 Countries by Total Food Consumption",
    x = "Country",
    y = "Total Consumption", 
    caption = "by Isaiah Ramirez, 4/27/2025, source:tidytuesday 2020-02-18"
  ) 
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
consumption_summary <- fcc %>%
  group_by(country, food_category) %>%
  summarise(total_consumption = sum(consumption, na.rm = TRUE)) %>%
  ungroup()

```
  



```{r, echo=FALSE, message=FALSE, warning=FALSE}
top_consumption <- consumption_summary %>%
  filter(country %in% top5_countries$country)

```




```{r, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
library(tidyverse)


top5_per_food <- top_consumption %>%
  group_by(food_category) %>%
  slice_max(order_by = total_consumption, n = 5) %>%
  ungroup() %>%
  arrange(food_category, desc(total_consumption)) # Arrange nicely

top5_per_food


```


```{r, echo=FALSE}
#| fig-height: 10
#| fig-width: 10
ggplot(top5_per_food, aes(x = total_consumption, y = fct_reorder(country, total_consumption))) +
  geom_point(size = 2, color = "darkred") +
  geom_text(aes(label = round(total_consumption, 1)), hjust = -0.2, size = 4) +
  facet_wrap(~ food_category, scales = "free_y") +
  scale_x_continuous(limits = c(0, 600)) +   # extend x-axis to 450
  labs(
    title = "Top 5 Countries by Food Category Consumption (Labeled)",
    x = "Total Consumption",
    y = "Country",
    caption = "by Isaiah Ramirez, 4/27/2025, source: tidytuesday 2020-02-18"
  ) +
  theme_minimal()

```







```{r, echo=FALSE, message=FALSE, warning=FALSE}
consumption_summary <- consumption_summary %>%
  mutate(country = case_when(
    country == "USA" ~ "United States of America",
    country == "Vietnam" ~ "Viet Nam",
    TRUE ~ country
  ))

```





```{r echo=FALSE, warning=FALSE, message=FALSE}
#| fig-height: 15
#| fig-width: 15
library(tidyverse)
library(sf)
library(rnaturalearth)


world <- ne_countries(returnclass = "sf") %>%
  select(name, geometry) %>%
  mutate(name = case_when(
    name == "United States of America" ~ "USA",
    name == "Bosnia and Herz." ~ "Bosnia and Herzegovina",
    name == "Czechia" ~ "Czech Republic",
    name == "Taiwan" ~ "Taiwan. ROC",
    TRUE ~ name
  ))

# Join and wrangle
world_food <- world %>%
  left_join(
    fcc %>%
      group_by(food_category) %>%
      mutate(consumption = (consumption - mean(consumption, na.rm = TRUE)) / sd(consumption, na.rm = TRUE)) %>%
      ungroup(),
    by = c("name" = "country")
  ) %>%
  pivot_wider(names_from = food_category, values_from = consumption) %>%
  select(-`NA`) %>%
  pivot_longer(cols = c(-name, -geometry),
               names_to = "food_category",
               values_to = "consumption")


ggplot(world_food) +
  geom_sf(aes(fill = consumption)) +
  scale_fill_viridis_c(option = "plasma", na.value = "grey90") +   
  facet_wrap(~ food_category) +
  theme_minimal() +
  theme(legend.position = "bottom") 
 



```




