---
title: "Solo -Proj."
editor: visual
---



```{r,echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(readxl)


covid_data <- read_excel("C:/Users/ramir/Downloads/CaseCountData (2).xlsx", 
                         sheet = "Case and Fatalities_2023", 
                         skip = 1)


head(covid_data)



```
```{r,echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(tigris)
library(sf)


counties_sf <- counties(state = "TX", cb = TRUE, class = "sf")

```


```{r,echo=FALSE, message=FALSE, warning=FALSE}

library(dplyr)


map_data <- counties_sf  %>%
  left_join(covid_data, by = c("NAME" = "County"))

```


```{r,echo=FALSE, message=FALSE, warning=FALSE}

covid_data <- covid_data %>%
  mutate(County = gsub(" County", "", County),    
         County = trimws(County),                 
         County = tolower(County))               

counties_sf <- counties_sf %>%
  mutate(NAME = tolower(NAME))                    
```

```{r,echo=FALSE, message=FALSE, warning=FALSE}
map_data <- counties_sf %>%
  left_join(covid_data, by = c("NAME" = "County"))

```

```{r,echo=FALSE, message=FALSE, warning=FALSE}

colnames(covid_data) <- c("County", "Confirmed_Cases", "Probable_Cases", "Fatalities")

```
```{r,echo=FALSE, message=FALSE, warning=FALSE}
map_data <- counties_sf %>%
  left_join(covid_data, by = c("NAME" = "County"))

```

```{r,echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(readxl)
library(tigris)
library(sf)
library(ggplot2)
library(viridis)
ggplot(map_data) +
  geom_sf(aes(fill = Confirmed_Cases)) +
  scale_fill_viridis_c(option = "plasma", na.value = "gray90") +
  labs(
    title = "Texas COVID-19 Confirmed Cases by County (2023)",
    fill = "Confirmed Cases",
    caption = "By Isaiah Ramirez, 4/30/2025, Source:https://www.dshs.texas.gov/covid-19-coronavirus-disease-2019/texas-covid-19-data"
  ) +
  theme_minimal()+
  theme(
    axis.text = element_blank(),    
    axis.ticks = element_blank(),   
    panel.grid = element_blank()   
  )

```


