---
title: "Mulivariate Viz"
---

Use this file for practice with the **mulivariate viz** in-class activity.  Refer to the class website for details.
```{r}
# Import and check out data
education <- read.csv("https://mac-stat.github.io/data/sat.csv")
```

```{r}
library(tidyverse)

# Import data
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") |> 
  mutate(date = as.Date(date))  

# Check out the first 6 rows
# What are the units of observation?
head(weather)
```



```{r}
# Import and check out data
education <- read.csv("https://mac-stat.github.io/data/sat.csv")
head(education)
```


```{r}
ggplot(education , aes( x = sat)) +
geom_density()
  
#This is basically telling me
```
```{r}
# Construct a plot of sat vs expend
ggplot(education , aes(y = sat , x  = expend)) +
geom_point() +
# Include a "best fit linear regression model" (HINT: method = "lm")
geom_smooth(method = "lm")
```
```{r}
# Construct a plot of sat vs salary
ggplot(education , aes(y = sat , x  = salary)) +
geom_point() +
# Include a "best fit linear regression model" (HINT: method = "lm")
  geom_smooth(method = "lm")

#so the more we spend, the worse the sat scores seem to get.
```

```{r}
ggplot(education, aes(y = sat, x = expend, color = fracCat)) + 
  geom_point() + 
  geom_smooth(method = "lm")
```

```{r}
# Change the code in order to construct a line plot of temp3pm vs date for each separate location (no points!)
ggplot(weather, aes(y = temp3pm, x = date, color = location)) + 
  geom_line()
```

```{r}
# Plot the relationship of raintomorrow & raintoday
# Change the code in order to indicate this relationship by location
ggplot(weather, aes(x = raintoday, fill = raintomorrow)) + 
  geom_bar(position = "fill") + 
  facet_wrap(~ location)
```
```{r}
ggplot(education, aes(x = sat, fill = fracCat)) + 
  geom_density(alpha = 0.5)
```
```{r}
stars(plot_data,
  flip.labels = FALSE,
  key.loc = c(10, 1.5),
  cex = 1, 
  draw.segments = TRUE
)
```

